language: node_js
node_js:
- '4.2.1'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: wcandillon@gmail.com
  api_key:
    secure: l4LEL/0daepsv4uekqok1gpBtzN5xNOus25fYEWG7zcHcIop2SotTZ5Exn1hxtGxfzBlEYQm/RhV+m0FQMLOE5Ywf68m6Lw+ZH1UUhT9ThfMD+7hjGsfQTQZ23SK1DQ3/68cU/JeuaPR++w5Snt+llZnDCG8UzWFbtjV5SyWFJ0=
  on:
    repo: wcandillon/swagger-js-codegen
    branch: master
    node: '0.11'
