language: node_js
node_js:
- '0.11'
- '0.10'
before_script:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: w@28.io
  api_key:
    secure: g+DjrtGRz4W7bvcCrJT3Oa80SFF/9TL+zP0rmTq36ANHNz0EyPV8epanL26RmQj+QA5XnHqzK1kFjFURrVncLJZdHXIdOSalaB5k8yRgpLEMETQvmTUfe6rWNTaEndKTjrUyWhHqceK4QlSrcv3VIq8loObimqaH7J1K3fZ7XgQ=
  on:
    branch: master
    repo: wcandillon/swagger-js-codegen
    node: 0.11
dd:
  secure: hW1GBxGDYcGnv0Bk1L9SCWBCcQFHrFYFvIpjWD1xv+L29+085TMDXOJA82dvbUZ2xCKRMsdXYrqg/luiOB92gXZrt/ZcEIk0EICI3rr9/2a3GqKThv0jR4V6wKkzFphgnDFSsMGAqxiHG+JE3K8F4MfMcb9IoBkfeUZDBHZ4gPA=
